### ISSUE TITLE
create date parsing is broken when listing clusters

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/gsctl#10]
When creating a cluster the time format for the `create_date` field is something like this.

```
2016-12-05T15:41:46.965138231+01:00
```

At the moment the API allows to set the create date explicitly when creating clusters. On Leaseweb we have also these formats. 

```
2016-11-10T10:00:00.000Z
2016-10-19T16:55:26.515752326Z
```

`gsctl` expects the go time format to be this. 

```
2006-01-02T15:04:05.000Z
```

See https://github.com/giantswarm/gsctl/blob/master/util/datetime.go#L15

In case a cluster is now created without providing a value for the `create_date` field, `gsctl` fails to parse the create date when listing clusters. 

```
ID            NAME          CREATED             ORGANIZATION
xh3b4sd-test  xh3b4sd-test  0001 Jan 01, 00:00  test-org
```

We should

1. ensure one definite time format in the cluster service
2. properly parse the create date without assuming some magic format beforehand and apply the format of choice after parsing the date properly

@marians

**Comment by xh3b4sd** [comment]
See https://github.com/giantswarm/cluster-service/issues/32 to track `1.`.

**Comment by marians** [comment]
I'm kind of reluctant to solve this on the client side. We should not have anything but UTC dates/times in our backends.

**Comment by xh3b4sd** [comment]
This does not change the fact that the implementation of time parsing in the client is faulty. The client should simply parse the time string it receives and formats the time to whatever he think is right. Applying magic regular expressions on unknown strings makes no sense as we see. Because this implementation is now broken when the backend is not consistent. Packages should not rely that much on internal knowledge of other systems. That is why we have types for. Using them makes life a little bit more easy in most cases.

**Comment by marians** [comment]
I know that the current implementation isn't cool. Call it a quality trade-off when writing my first Go application.

**Comment by xh3b4sd** [comment]
This is all good. No worries. The issue is about describing a problem which in turn should be fixed at some point.

**Comment by marians** [comment]
TODO:

- Add unit test
- Make parsing more robust to handle different formats

**Comment by marians** [comment]
See also https://github.com/giantswarm/cluster-service/pull/130

**Comment by marians** [comment]
Closed via https://github.com/giantswarm/gsctl/issues/73
