### ISSUE TITLE
Command to show guest clusters details

### ISSUE THREAD

**Issue by lukaseichler** [giantswarm/gsctl#105]
As a user of the gsctl I would like to know the overall resources configuration of a guest cluster so I can better manage these clusters.

Futhermore I would like to see the overall guest cluster resource allocation in addition to the overall available resources for guest clusters in the host cluster.

**Comment by marians** [comment]
@lukaseichler Do you have a command syntax in mind to retrieve the information you would like to access? (I do, but I want to hear it from you 😄 )

Another question: What exactly do you mean here with "guest cluster resource allocation"? Sounds to me like you mean current usage, but I'd like to make sure.

**Comment by marians** [comment]
Related: giantswarm/giantswarm#1915

**Comment by marians** [comment]
Usage spec for `gsctl show cluster`:

```
$ gsctl show cluster --help
Shows details for a cluster.

Usage:
  gsctl show cluster <cluster-id> [flags]

Flags:
  -h, --help   help for cluster
Global Flags:
...
```

Output spec for `gsctl show cluster`:

```
ID: vxvc7
Created: 2017 Aug 29, 04:26 UTC
Organization: giantswarm
Kubernetes API endpoint: https://api.vxvc7.k8s.ginger.eu-central-1.aws.gigantic.io
Release version: 0.3.0
Workers: 3
Worker instance type: m3.large
CPU cores in workers: 6
RAM in worker nodes: 22.5G
Storage in worker nodes: 96G
```

Displaying worker details will be done using a new command `gsctl list workers` (to be specified).

**Comment by marians** [comment]
This has been released in https://github.com/giantswarm/gsctl/releases/tag/0.9.0
