### ISSUE TITLE
Change gsctl CI pipeline from Travis to CircleCI

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#107]
We use CircleCI for most other repos, so it would help to unify this.

codedov.org integration is to be figured out.

**Comment by marians** [comment]
This requires changes in our unit tests, as kubectl isn't available in the architect docker container.

**Comment by oponder** [comment]
Or perhaps we could download kubectl before running the test?

**Comment by marians** [comment]
The problem is that architect runs tests in a Docker container, and I don't see a way to mount extra stuff to that container.

**Comment by marians** [comment]
Travis is removed now with #207
