### ISSUE TITLE
gsctl create keypair/kubeconfig should have an option for an output folder

### ISSUE THREAD

**Issue by deichten** [giantswarm/gsctl#113]
### What did you do/observe?
While creating keypairs or kubeconfig for colleagues who don't have and shouldn't have access to happa I noticed that creating a kubeconfig always overwrites my current kubeconfig. Even passing a different `--config-dir` doesn't help since I'll have to log in again.

What I'm now usually doing is creating keypairs, reading the output and copying/moving the files to shared keybase folder. 

### What did you expect?
Creating keypairs/kubeconfig should have an option to define the output folder, e.g. via `--output`.

### Details
- Operating system, platform/architecture: Mac Sierra (10.12.6) on MacBookPro13,3
- Output of `gsctl version`:
```
Version:     0.7.0
Build date:  2017-08-04T08:52:19Z
```
- Any other details required to reproduce the problem: None

**Comment by marians** [comment]
@deichten Thanks for the suggestion. (Unfortunately so far it slipped through under the radar.)

The use case you describe makes sense to me. In happa, we support this better I think. There you create a self-contained kubeconfig file which you can download and then hand to users.

In gsctl the `--config-dir` flag only influences where gsctl stores its _own_ config. The kubectl config file is considered something else.

But: gsctl obeys the `KUBECONFIG` environment variable. If you point that to a non-existing path, you should be able to create a new kubectl config file. Example:

```
KUBECONFIG=./mydir/kubeconfig.yaml gsctl create kubeconfig -c <cluster> --ttl 1 --description "Test for creating a kubeconfig file"
```

However, the key pairs will end up in your standard dir '~/.config/gsctl`. You could change that by using `--config-dir=./mydir`, but then you would also have to use `--endpoint` and `--auth-token` to tell gsctl which endpoint and token to use.

**Comment by marians** [comment]
So with the above info, I'm not sure if we want another way to override the output folder. Or if we rather want an option to create a self-contained kubeconfig file including key pair and CA data, like happa creates it. The user could define the path and file name for this using one flag.

**Comment by nexeck** [comment]
I would like to have an option where i am able to create self-contained kubeconfig files (With an option where this file should be saved), like happa creates it.

**Comment by marians** [comment]
This has been merged and will be released soon. See linked PR for details.
