### ISSUE TITLE
gsctl create kubeconfig should have an option for defining the k8s context name

### ISSUE THREAD

**Issue by deichten** [giantswarm/gsctl#114]
### What did you do/observe?
Every new kubeconfig which gets created does come with the name `giantswarm-XXXXX`. Memoizing this sometimes can be hard. Therefore I usually rename those manually afterwards to indicate the purpose, e.g. `prod-eu-west`. 

### What did you expect?
Would be very handy to have an option to pass in the context name already during creation, e.g. via `--context-name.

### Details
- Operating system, platform/architecture: MacOS Sierra (10.12.6)
- Output of `gsctl version`: 
```
Version:     0.7.0
Build date:  2017-08-04T08:52:19Z
```
- Any other details required to reproduce the problem: None

**Comment by marians** [comment]
@deichten Thank you for this suggestion, which makes sense to me.

**Comment by marians** [comment]
Now in `master`, will be released soon. The flag name is `--context`.
