### ISSUE TITLE
There should be an environment variable to set an auth token (GSCTL_AUTH_TOKEN)

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#121]
As described in https://github.com/giantswarm/gsctl/issues/47#issuecomment-332180593, endpoint selection will become available via an environment variable, as an alternative to setting it via a flag or selecting it via a command.

For consistency and security reasons, it would make sense to allow specifying an environment variable `GSCTL_AUTH_TOKEN` as an alternative to setting the `--auth-token` flag.

The security benefit would be that the token would not have to be duplicated over and over to the command line.

**Comment by marians** [comment]
@pipo02mix Can you give some detail why this is in the inbox? Any use case?

**Comment by pipo02mix** [comment]
Why should I know? 🤔

**Comment by marians** [comment]
@pipo02mix Because you added a note in the SIG UX board referencing this issue.

![image](https://user-images.githubusercontent.com/273727/64233546-cb51f980-cef4-11e9-8a4b-b404b6974390.png)

**Comment by marians** [comment]
This is coming from a customer that would like to run gsctl in a Kubernetes pod. While a command line flag would be readable in the Pod manifest in clear text, an environment variable could be set via a Secret.
