### ISSUE TITLE
Support shorter TTLs

### ISSUE THREAD

**Issue by oponder** [giantswarm/gsctl#137]
Our API takes the TTL for a keypair in hours: https://docs.giantswarm.io/api/#operation/addKeyPair

However in `gsctl create kubeconfig`, the `ttl` flag is always in days.

It would be nice to also support a smaller time interval. Usually I only need 1 hour in a customers cluster to verify an issue. 

Note this is not a bug, just a feature request for some way to create keypairs with a ttl of less than 1 day.

**Comment by marians** [comment]
What do you think about allowing the use of the typical time unit syntax like `1h`, `1d`, `1w` etc?

We should make "hour" the default unit though, if no unit is given. This is of course a behaviour change that needs proper announcement.

**Comment by oponder** [comment]
Sounds good to me! 

I'm thinking it might be better to error with a clear message if someone doesn't provide a unit. That way there is no ambiguity and people will learn soon enough to include the unit.

`"TTL is invalid. Please provide a unit. e.g. 1h, 1d, 1w"`

But no strong feelings about that

**Comment by marians** [comment]
Throwing an error is also fine with me. It's more consistent and predictable that way.

**Comment by marians** [comment]
This can be tested/reviewed in https://github.com/giantswarm/gsctl/pull/228

**Comment by marians** [comment]
Done
