### ISSUE TITLE
'list keypairs' should list key pairs of all clusters by default

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#142]
As a consistency rule, all `gsctl list <noun>` commands should work independent of a guest cluster by default.

For `gsctl list keypairs`, currently the `-c <cluster-id` or `--cluster <cluster-id>` appendix is required to specify which cluster to list key pairs for.

The command should work cluster-independent, too. So if no cluster specified, key pairs from all clusters should be listed. In that case, a cluster ID column would be required.

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` won’t be further developed and will be replaced with `kubectl gs`.
