### ISSUE TITLE
Worker node limit should be taken into consideration when creating clusters

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#155]
Now that we have an API endpoint to acquire information on the installation, we know how many worker nodes per cluster are supported. See https://docs.giantswarm.io/api/#operation/getInfo

When creating clusters, this limit should be taken into consideration and the user should get an error message when trying to create a too big cluster.

**Comment by marians** [comment]
The validation part of this is expected to happen on the API side. We can optionally use the available info to inform the user beyond the error message.

**Comment by marians** [comment]
Upstream issue: https://github.com/giantswarm/giantswarm/issues/2918

**Comment by axbarsan** [comment]
Both https://github.com/giantswarm/giantswarm/issues/6572 and https://github.com/giantswarm/giantswarm/issues/6573 have been fixed, so gsctl is now handling these errors properly
