### ISSUE TITLE
Let output of `gsctl completion bash` be sourcable

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#160]
To simplify loading of gsctl completion files for bash, we should support this:

    source <(gsctl completion bash)

So a subcommand `gsctl completion bash` should output completion code for bash to STDOUT.

This means we would probably have to remove the current function of `gsctl completion`.

We'll have to specify what `gsctl completion zsh` should do.

**Comment by sjentzsch** [comment]
Bump.

Even the latest version won't work for me:

```
sjentzsch@SJ-Notebook:~$ source $(gsctl completion bash --stdout)
bash: #: No such file or directory
```

**Comment by marians** [comment]
Thanks for the hint!

This doesn't make for a good first line in the output:

```
# bash completion for gsctl                                -*- shell-script -*-
```

**Comment by marians** [comment]
@sjentzsch Can you try this please?

```
source <(gsctl completion bash --stdout)
```

**Comment by sjentzsch** [comment]
@marians I see, yes, that one works. Thanks!

**Comment by marians** [comment]
Done
