### ISSUE TITLE
Improve incorrect api endpoint handling

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/gsctl#177]
### What did you do/observe?
```
$ ./gsctl login joseph@giantswarm.io -e https://happa.[REDACTED]
Password for joseph@giantswarm.io on https://happa.[REDACTED]: 
invalid character '<' looking for beginning of value
```

### What did you expect?
An error message that prompted me to realise I am bad at copy-and-pasting (happa URL, not api URL).

### Details

- Operating system, platform/architecture:
```
$ uname -a
Linux dev-vm 4.14.4-coreos #1 SMP Wed Dec 6 04:03:17 UTC 2017 x86_64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz GenuineIntel GNU/Linux
```
- Output of `gsctl version`:
```
$ ./gsctl version
Version:     0.9.2
Build date:  2017-12-07T09:15:51Z
```
- Any other details required to reproduce the problem:
NO DETAILS FOR YOU

**Comment by marians** [comment]
We should try to improve the error message especially here in the login command.

**Comment by marians** [comment]
This is being addressed in https://github.com/giantswarm/gsctl/pull/197

**Comment by marians** [comment]
#197 is merged.
