### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/gsctl#179]
Feature request: I want to run gsctl on coreos, an image would be helpful (this is largely a reminder to myself)

**Comment by JosephSalisbury** [comment]
@marians thoughts? if we don't do it here, i'll do it personally

**Comment by marians** [comment]
I don't see a reason not to do it. What would you expect in terms of tags? `latest` whenever we merge something into master, or whenever we do a release? Plus semver version tags?

**Comment by JosephSalisbury** [comment]
Latest tracking master makes sense for me.
For my personal workflow, I'd like semver version tags (so I can alias a stable version).

**Comment by marians** [comment]
Ok, latest=master means no extra work.

The semver tagging I don't know immediately how to automate that. Unless you have an idea, I'd leave that open in a first step.

**Comment by JosephSalisbury** [comment]
I'd have to dig into gsctl deployments further. Feel free to throw this to sig-releng.

**Comment by marians** [comment]
Moving this out of the board, as we aren't pursuing this. @JosephSalisbury if you don't want to do this ay time, feel free to close.

**Comment by JosephSalisbury** [comment]
Not on my radar right now.
