### ISSUE TITLE
Accept cluster name as argument, as an alternative to a cluster ID

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#188]
Some users seem to expect to be able to use cluster names in `gsctl` commands. E. g.

    gsctl scale cluster "My cluster name"

Currently, cluster names are not required to be unique, so there _might_ be cases where the name would be ambigious. That case could be handled with a specific error message.

To resolve a cluster name to its ID, we would require an additional call to `GET /v4/clusters/`.

**Comment by marians** [comment]
If we can do this in half a day, let's do it.

**Comment by axbarsan** [comment]
Commands that need this implemented

- [ ] Create keypair
- [ ] Create kubeconfig
- [ ] Create nodepool
- [ ] Delete cluster
- [ ] Delete nodepool
- [ ] List keypairs
- [ ] List nodepools
- [ ] Scale cluster
- [ ] Show cluster
- [ ] Show nodepool
- [ ] Update cluster
- [ ] Update nodepool
- [ ] Upgrade cluster

**Comment by axbarsan** [comment]
All the PRs have been merged. Testing each command again, on `master`, before closing this

**Comment by axbarsan** [comment]
Tested again, every command is working like before 👍
