### ISSUE TITLE
gsctl list releases sorting should be reversed (newest last)

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#190]
Currently it's oldest last, should be oldest first, to have the latest visible.

**Comment by teemow** [comment]
Imo the list would also be much easier to read if it would come by default in a compact "table view". and then something like `gsctl show release --version 2.1.2` can list all the details of a particular release. Sorry for piggybacking this issue :)

**Comment by teemow** [comment]
@marians are we good here with the new `gsctl list releases`?

**Comment by marians** [comment]
Yes, thanks!
