### ISSUE TITLE
Command to display cluster metrics

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#195]
We are currently working on making cluster metrics available via the API, to enable cluster owners to get a better understanding of resource usage and cluster state in general.

In fact the API docs already contain [more details](https://docs.giantswarm.io/api/#operation/getClusterMetrics) on the metrics provided first.

(This is becoming available gradually, depending on the provider and cluster age.)

In this first step, metrics are available for worker nodes only. There is a set of 15 metrics that is provided on a per-worker basis. The list of metrics is likely to grow/change in the future. As of now, all metrics provide absolute values. E. g. CPU usage (cpu_used) is the absolute number of CPUs being used.

Here is the current list of metrics as in the API docs:

- `container_count`: Number of containers running
- `pod_count`: Number of pods running
- `cpu_used`: Number of CPU cores currently used
- `ram_free`: Free memory in bytes
- `ram_available`: Memory available for new applications, in bytes
- `ram_cached`: Memory used for file caches, in bytes
- `ram_buffers`: Memory used for kernel buffers, in bytes
- `ram_mapped`: Memory used by mapped files, in bytes
- `node_storage_used`: Amount of local storage used in bytes
- `network_rx`: Incoming data volume (Rx) in bytes per second
- `network_tx`: Outgoing data volume (Tx) in bytes per second
- `resource_cpu_requests`: Sum of CPU requeszs for containers
- `resource_cpu_limits`: Sum of CPU limits for containers
- `resource_ram_requests`: Sum of memory requests for containers
- `resource_ram_limits`: Sum of memory limits for containers

### Design considerations

- A dedicated command: We think there should be a dedicated command to display the metrics for one cluster, independent of other details like currently printed by `gsctl show cluster`. This way the potentially complex information output can be kept mostly homogeneous. Also this would lean nicely to observing the command's output with a tool like `watch`.

- Absolute vs. relative values: Should numbers be presented as absolute figures, or in percentages of the maximum possible?

- Should units (e. g. `%`, `GiB`, `MiB/Sec`) be displayed with each value, or in column headers, or elsewhere? Only really applicable for absolute figures.

- What accuracy is needed? Could absolute numbers be rounded to e. g. 3 significant digits (`1.23 GiB`)?

- The display of these metrics per worker node in form of a table appears obvious. As an identifier, the worker node IP address would be used (which is the identifier currently provided by the API). The table would be sorted by that identifier. User-defined sorting using different columns might be provided.

- As a table containing all metrics can become very wide, by default we would only display a subset of what we consider the most relevant metrics. Output of all metrics could be enabled using a command line option. Also useful would be a way to select columns individually. For that however we would need a reference of the technical column names (`network_tx´ vs. `Outgoing network traffic`).

- Should we visualize figures e. g. using bars out of unicode symbols?

- Do we need a summary of all values instead of or in addition to individual node values?

**Comment by marians** [comment]
As a first reference, here is a data table showing mostly absolute values. Some ram_* metrics are not included.

The draft also features both uppercase "friendly" headers and the technical metrics names as headers, to show the difference side by side.

```
NODE       CPU USED  CPU REQUESTS  CPU LIMITS  ram_free  ram_available  resource_ram_requests  resource_ram_limits  pod_count  container_count  node_storage_used  network_tx
10.0.3.4       34 %           0.9         1.2   437 MiB      1.231 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
10.0.3.5       22 %           0.9         1.2   424 MiB      1.146 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
10.0.3.6       34 %           0.9         1.2   437 MiB      1.231 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
10.0.3.7       22 %           0.9         1.2   424 MiB      1.146 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
10.0.3.8       34 %           0.9         1.2   437 MiB      1.231 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
10.0.3.9       22 %           0.9         1.2   424 MiB      1.146 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
10.0.3.10      34 %           0.9         1.2   437 MiB      1.231 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
10.0.3.11      22 %           0.9         1.2   424 MiB      1.146 GiB              1.231 GiB            1.577 GiB         12               18           44.2 GiB  567 KiB/Sec
```

**Comment by xh3b4sd** [comment]
I just tried to fake the impression I would get in my terminal. Did you design this on purpose for 15 inch monitors? Displays must not be smaller with this layout to get a readable rendered table in the terminal. 

<img width="1440" alt="screen shot 2018-02-14 at 19 07 26" src="https://user-images.githubusercontent.com/552769/36220306-5ef89f9e-11ba-11e8-8a7d-c13abcee356b.png">

**Comment by pipo02mix** [comment]
> Absolute vs. relative values: Should numbers be presented as absolute figures, or in percentages of the maximum possible?

It depends on the metric, your table example is pretty good. Maybe some metrics can have both like 
ram_free could be 437MiB (10%)

> Should units (e. g. %, GiB, MiB/Sec) be displayed with each value, or in column headers, or elsewhere? Only really applicable for absolute figures.

If all the rows show the same unit then I would add it the header, although it may extend the name length too much

> What accuracy is needed? Could absolute numbers be rounded to e. g. 3 significant digits (1.23 GiB)?
IMO in general integers should be fine for most of the metrics

> As a table containing all metrics can become very wide, by default we would only display a subset of what we consider the most relevant metrics. Output of all metrics could be enabled using a command line option. Also useful would be a way to select columns individually. For that however we would need a reference of the technical column names (network_tx´ vs.Outgoing network traffic`).

Also, I would consider applying ellipse for long node names

**Comment by marians** [comment]
@xh3b4sd [It](https://github.com/giantswarm/gsctl/issues/195#issuecomment-365684996) is a first mockup to have something to talk about. As I wrote under *Design considerations* above, `a table containing all metrics can become very wide...` and we need a solution for that. I welcome your suggestions on which metrics you would consider most important, to be shown by default.

**Comment by marians** [comment]
Added "Do we need a summary of all values instead of or in addition to individual node values?" to the design considerations

**Comment by marians** [comment]
Closing, as the metrics API has been shut down meanwhile and a replacement is being worked on.
