### ISSUE TITLE
Help command shown after create a cluster is not useful

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/gsctl#198]
### What did you do/observe?
When you create a new cluster the output help text indicates 
```
gsctl create kubeconfig --cluster=<cluster-id>
```
But nowadays all clusters are with RBAC enabled, so the command creates a user that has not right to perform any action

### What did you expect?

Expose the command with the organization group and the ttl
```
gsctl create kubeconfig --cluster=<cluster-name> --certificate-organizations system:masters --ttl 1
```

**Comment by marians** [comment]
As the second example creates a powerful key pair, we might want to explain a bit more.

- The key pair will have admin rights.
- Check the reference/help for more details on how to create a key pair with different privileges.

**Comment by pipo02mix** [comment]
done
