### ISSUE TITLE
release.sh should not upload to s3 if it fails to create the github release

### ISSUE THREAD

**Issue by oponder** [giantswarm/gsctl#209]
### What did you do/observe?

When creating a release, using `./release.sh` if the step that creates the github release fails, the script continues on to upload binaries to S3.

### What did you expect?

I expected it to error out so that I could recover, avoid potentially inconsistent state, and re-run the script.

### Details

- Operating system, platform/architecture:
- Output of `gsctl version`:
- Any other details required to reproduce the problem:

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` won’t be further developed and will be replaced with `kubectl gs`.
