### ISSUE TITLE
Panic on line create_kubeconfig.go#L366: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by oponder** [giantswarm/gsctl#217]
https://github.com/giantswarm/gsctl/blob/69435ca94008f6086225f9645c495dfa573926d1/commands/create_kubeconfig.go#L366

Apparently this line can panic. Is it possible? I wouldn't think so. So I am currently still verifying the `gsctl` version with the customer.

**Comment by JosephSalisbury** [comment]
If `apiResponse` is nil, that could panic.

**Comment by oponder** [comment]
It can't be because:

```
	if err != nil {
		var errorMessage string
		if apiResponse != nil {
			errorMessage = fmt.Sprintf("HTTP status: %d", apiResponse.StatusCode)
		} else {
			errorMessage = "No response received from the API"
		}
		return result, microerror.Maskf(err, errorMessage)
	}
```

**Comment by JosephSalisbury** [comment]
Hmm, that doesn't work then. Maybe older gsctl version, so the check for apiResponse not being nil isn't there?

**Comment by marians** [comment]
@oponder Have you verified from which gsctl version that was coming?

**Comment by marians** [comment]
Needs verification

**Comment by marians** [comment]
We think we solved this
