### ISSUE TITLE
'gsctl login' should allow to switch accounts when logged in

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#22]
I am currently logged in as `user-a@example.com` (maybe not aware of it). Now I want to use `gsctl login user-b@example.com` to log in as another user. Note that the two IDs (emails) are different.

Currently this yields the error message `Error: You are already logged in`.

Instead it should implicitly log out the user and log in as if the user wasn't logged in before.

**Comment by oponder** [comment]
@puja says it would also be nice to be able to be logged in to multiple accounts at once. I created a note about this in the inbox.

**Comment by oponder** [comment]
@puja: Using aliases and the global config flags for api-endpoint and config directory location should solve the problem of being logged in in multiple places.

**Comment by marians** [comment]
Solved in #84
