### ISSUE TITLE
Garbage collection for CA files

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#233]
When deleting outdated key pair files (certificate and key), we leave the CA file behind, as it may still be in use by another key pair.

We could add an additional check to see whether there actually is another key pair referencing the same cluster (by using the file name prefix). If that's not the case, the CA file can be deleted, too, as it will be downloaded again whenever a new key pair is created.

**Comment by marians** [comment]
This may be facilitated by https://github.com/giantswarm/gsctl/issues/294 . When checking kubectl context, server, and user entries, it might become more achievable to also determine whether the CA is still needed.

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` won’t be further developed and will be replaced with `kubectl gs`.
