### ISSUE TITLE
Unify access forbidden (403) error handling

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#272]
After the client migration we have to make sure the error handling for the HTTP 403 case (Access Forbidden) is handled in a unified way everywhere. An example from `list clusters`:

```
$ gsctl list clusters -e codename
Access Forbidden
The client has been denied access to the API endpoint with an HTTP status of 403.
Please make sure that you are in the right network or VPN. Once that is verified,
check back with Giant Swarm support that your network is permitted access.
```

And `create kubeconfig`:

```
$ gsctl create kubeconfig --ttl 1d --certificate-organizations="system:masters" -e codename -c f24sd
HTTP status: 403: invalid character '<' looking for beginning of value
```

The specific error message here comes from the attempt to parse an HTML page as JSON, but it is misleading.

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` is officially deprecated and will be replaced with `kubectl gs`.
