### ISSUE TITLE
Don't print command usage if user isn't logged in

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#28]
I'm currently not logged in and try to list clusters:

```nohighlight
$ gsctl list clusters
Error: You are not logged in. Use 'gsctl login' to log in.
Usage:
  gsctl list clusters [flags]

Global Flags:
      --api-endpoint string   The URL base path, to access the API (default "https://api.giantswarm.io")
      --auth-token string     Authorization token to use for one command execution
  -v, --verbose               Print more information
```

Printing the usage info for `gsctl list clusters` here only adds confusion and should be prevented.

## Solution

The above problem occurs because we still use cobra's `PreRunE` field instead of `PreRun` for the validation before command execution. That way, when an error occurs, cobra automatically shows the usage info.

We should change to use `PreRun` for the auth validation, then print a nice error message in case the user is not logged in and exit with code 1.

**Comment by webwurst** [comment]
Just wanted to file this :)

**Comment by marians** [comment]
This is no longer valid.
