### ISSUE TITLE
Key pair garbage collection could also delete kubectl contexts

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#294]
### What did you do/observe?

When garbage collection removes expired key pairs from the file system, the server and context entries remain in the kubectl config file (also known as kubeconfig).

As a result, `kubectl config get-contexts` may result in an ever-growing list of contexts. The problem is worse for users dealing with many different clusters or creating and deleting clusters frequently.

### Proposed solution

When garbage collection finds an expired certificate, the certificate and the matching key is deleted.

1. As a next step, we could also delete `user` entries in the kubeconfig referencing non-existing key/cert files.
2. Then we should find the `context` entries referencing the user we just deleted and delete those, saving the `cluster` reference.
3. Then we should delete the `cluster` entries we just found are no longer referenced by a context.
4. We can then delete the CA certificate files no longer referenced by any cluster entry.

**Comment by marians** [comment]
I'd like to know from users whether you think that tinkering with kubeconfig entries in the described manner is something you would like, or whether you'd rather have control over what's deleted.

**Comment by puja108** [comment]
Users with OIDC/AAD auth are using our `cluster` and the CA to create their context with the OIDC users they set up. So I'd be careful with 3 & 4, you might break some custom configs if you mistakenly delete those entries.

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` won’t be further developed and will be replaced with `kubectl gs`.
