### ISSUE TITLE
Machine-readable output

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#297]
Working with `gsctl` command output in automation usually requires massaging the output using utilities like `grep`, `awk`, `tail` etc., in order to reduce the output to a relevant item like an auth token, an API endpoint, only a cluster ID column.

Is this enough? If not, how should the output capabilities be improved to work better in scripts and automation?

Some things we know and potentially like from other CLIs we use:

- JSON output (e. g. kubectl)
- YAML output (e. g. kubectl)
- Individually selecting the columns to output for a table (`fleetctl list-units --fields ...`)
- Filtering list items by some criteria

Please let us know what would help you. Comments explaining concrete use cases would be most helpful.

**Comment by marians** [comment]
As I just learned from a user, AWS and Azure CLIs use [JMESPath](http://jmespath.org/). That could actually kill several birds with one stone.

**Comment by ChristianWeissCG** [comment]
Outputing in a format like JSON is very welcome. I like https://stedolan.github.io/jq/ for parsing JSON at command line.

**Comment by jrich523** [comment]
I too would like to see a machine readable output. This ticket seems fairly old, any progress? blockers? questions?

**Comment by marians** [comment]
@jrich523 It's been a matter of priorities mostly. Can you give us a bit of detail regarding which command(s) you would like us to start with, and how you would use the output?

**Comment by jrich523** [comment]
Well for example im using the output in powershell so right now i hvae to do this to parse the output

```
$clusters = gsctl list clusters | %{ $_ -replace "\s{2,}",":"} | ConvertFrom-Csv -Delimiter :  
$details = $clusters | %{ (gsctl show cluster $_.id  | %{ $_.replace(":","=")}) -join "`n" }| ConvertFrom-StringData
```

Which isnt the end of the world, but it took time to screw with, and would be nice if i could just do something like (from Kubectl)

`$clusters = gsctl list clusters -o json | convertfrom-json`

**Comment by marians** [comment]
Please have a look at https://github.com/giantswarm/gsctl/pull/431 for an implementation of JSON output in `gsctl list clusters`.

**Comment by marians** [comment]
gsctl v0.17.0 has been released, including the JSON output option for `gsctl list clusters` and `gsctl list keypairs`. We aim to implement this for further `gsctl list <noun>` commands.

Feel free to give feedback here or in new issues, however this one will be closed for now.
