### ISSUE TITLE
Suggested commands should contain options like --endpoint when required

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#38]
From joe:

```
$ awsgsctl create cluster --owner=joseph
Requesting new cluster for organization 'joseph'
New cluster with ID 'w1hmn' is launching.
Add key-pair and settings to kubectl using

    gsctl create kubeconfig —cluster=w1hmn
```

It would be extra cool if the suggested command would use the same executable name as the user did.

**Comment by webwurst** [comment]
hm, but you don't know how `awsgsctl` is implemented. i would put out something like this:
```gsctl --api-endpoint=https://api-aws.giantswarm.io create kubeconfig --cluster=w1hmn```

**Comment by marians** [comment]
> hm, but you don't know how awsgsctl is implemented.

True. If it's an alias, e. g. for `gsctl --api-endpoint=https://api-aws.giantswarm.io`, the first comand line argument is still `gsctl` and not `awsgsctl`.

I agree, adding the `--api-endpoint` flag when necessary would bring us close.

**Comment by axbarsan** [comment]
Is this still needed, @marians  ?

**Comment by marians** [comment]
Still pretty much valid, with the exception that the flag named in my comment above (`--api-endpoint`) is now `--endpoint`.

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` won’t be further developed and will be replaced with `kubectl gs`.
