### ISSUE TITLE
Auth token redaction

### ISSUE THREAD

**Issue by bastiandg** [giantswarm/gsctl#536]
In the documentation I found out that you are sending every command line parameter back for statistics and other stuff. I was curious to see whether the password was redacted when you send it back. And it does: https://github.com/giantswarm/gsctl/blob/5730526c818ee0dd2fd491aa37352d7f9ca7af93/client/client.go#L186

But the redaction is only done for passwords. Not for auth tokens.

So when using this command:

```
gsctl --endpoint https://api.some.end.point.gigantic.io \
  create kubeconfig \
  --cluster xpsvd \
  --certificate-organizations system:masters \
  --auth-token dc71c38a-8600-11ea-be08-6314766e4007
```

the authentication data is still send to your telemetry server.

**Comment by marians** [comment]
Thanks for pointing this out! We are looking at it now.
