### ISSUE TITLE
Provide gsctl binaries for the ARM architecture

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#60]
Why not build another two binaries (32 and 64 bit)?

**Comment by marians** [comment]
There seems to be a larger variety of ARM architectures.

Some have a floating point unit and require `GOARM=7` to be set on build. Example: Raspberry Pi 2 and 3.

Other don't have that unit, so they require `GOARM=5`. Example: Raspberry Pi Zero.

Source: https://www.alexruf.net/2016/01/16/cross-compile-with-go-1-5-for-raspberry-pi.html (see comments)

**Comment by marians** [comment]
Users, please let us know here in case you'd want a pre-built binary for your ARM architecture, and if yes, what platform that is exactly.

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` is officially deprecated and will be replaced with `kubectl gs`.
