### ISSUE TITLE
Number of workers flag should default to 3 to match Happa

### ISSUE THREAD

**Issue by rossf7** [giantswarm/gsctl#68]
In create cluster --num-workers defaults to 2 but in Happa the default is 3. We should change gsctl to default to 3 nodes because this is more production ready.

e.g Our Ingress Controller deployment needs to schedule 3 pods on different nodes.

**Comment by puja108** [comment]
@marians mentioned this is a default in our API services not `gsctl`

**Comment by marians** [comment]
I agree that 3 is a better default value than 2.

Currently the situation is that `gsctl` doesn't apply any default value. It passes through to the API whatever the user sets. Then, some place behind the API, a minimum of 2 worker nodes is enforced.

We had internal discussion about this some time ago and decided we should allow users to create single node cluster, if they wish so. So the current API behaviour can be considered a bug to be fixed.

**Comment by rossf7** [comment]
@marians @puja108 thanks that makes sense and I agree users should be able to specify single node clusters if they wish. Closing in favour of https://github.com/giantswarm/giantswarm/issues/1502
