### ISSUE TITLE
No coloured output on Windows

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#7]
The windows version has coloured output specifically disabled, as tests showed that console output is drastically slowed down when enabling it.

The library we use for color is [fatih/color](https://github.com/fatih/color), which in turn uses [mattn/go-colorable](https://github.com/mattn/go-colorable) on Windows.

**Comment by marians** [comment]
Removing the `kind/bug` label, as this is hardly breaking expectations regarding functionality.

**Comment by marians** [comment]
Just tested again on WIndows 10 with a build where colors are enabled for windows. It works fine in Windows PowerShell:

![image](https://user-images.githubusercontent.com/273727/30958283-f0c1c338-a43c-11e7-8d8f-02cb65dd6341.png)

But this is the output on the "Command Prompt":

![image](https://user-images.githubusercontent.com/273727/30958338-167b3c26-a43d-11e7-9df4-bef8c7a66251.png)

Though I must admit that Windows instance has `concfg` installed with the Solarized theme. Maybe that doesn't work well in combination.

**Comment by snizhana-dynnyk** [comment]
Closing since `gsctl` is officially deprecated and will be replaced with `kubectl gs`.
