### ISSUE TITLE
Config file should have permission 0600, but has 0644

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#87]
#### Observed:

The configuration file we generate gets the permission mask `-rw-r--r--` which in theory allows read access to everyone.

Seen on Mac OS.

#### Expected:

Permission mask `-rw-------`.

We are setting the permissions to `0600` explicitly here https://github.com/giantswarm/gsctl/blob/master/config/config.go#L180

**Comment by marians** [comment]
Kind of weird, since we explicitly set the permission of the config file to `0600` (on creation):

https://github.com/giantswarm/gsctl/blob/master/config/config.go#L180

**Comment by marians** [comment]
Here is a test program I ran locally both on Mac OS and Ubuntu and got the expected results in both cases.

```go
package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	path := "./testfile"
	err := ioutil.WriteFile(path,
		[]byte("This is some content"),
		os.FileMode(0600))
	if err != nil {
		panic(err)
	}

	fileInfo, statErr := os.Stat(path)
	if statErr != nil {
		panic(err)
	}

	fmt.Printf("Permissions: %o (%s)\n",
		fileInfo.Mode().Perm(),
		fileInfo.Mode().Perm())
}
```

Execution and output (Mac OS):

```bash
$ go run main.go && ls -la testfile
Permissions: 600 (-rw-------)
-rw-------    1 marian  staff    20B Jun 16 09:01 testfile
```

**Comment by marians** [comment]
Another test program that first creates a directory structure and places the test file inside, just as it happens in gsctl. Again, this works as aéxpected and it doesn't reproduce the problem.

```go
package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

func main() {
	dirPath := "./dir/subdir"
	os.MkdirAll(dirPath, 0700)

	path := "./dir/subdir/testfile"
	err := ioutil.WriteFile(path,
		[]byte("This is some content"),
		0600)
	if err != nil {
		panic(err)
	}

	fileInfo, statErr := os.Stat(path)
	if statErr != nil {
		panic(err)
	}

	fmt.Printf("Permissions: %o (%s)\n",
		fileInfo.Mode().Perm(),
		fileInfo.Mode().Perm())
}
```

**Comment by xh3b4sd** [comment]
I think your problem is this: https://play.golang.org/p/-0a3TPn7P-.

**Comment by marians** [comment]
@xh3b4sd I tested both ways and it doesn't make a difference. See the test code above in https://github.com/giantswarm/gsctl/issues/87#issuecomment-308963124 ? It doesn't use `os.FileMode()`, but the permissions are all set as expected. When changing this to use `os.FileMode()`, it just works the same way.

**Comment by xh3b4sd** [comment]
What is the problem then?

**Comment by marians** [comment]
The problem is that the config file written by gsctl has permission 0644, but it should have 0600, and I can't explain why this happens.

**Comment by xh3b4sd** [comment]
Well, this is not visible from this issue though, but thanks for clarifying.
