### ISSUE TITLE
gsctl commands ignore --auth-token given via flag

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#92]
This should actually trigger a "not authenticated" error:
```
gsctl --api-endpoint=https://api-g8s.giantswarm.io list clusters --auth-token=sfdsdf
```

But it doesn't.

**Comment by oponder** [comment]
Same thing with `create kubeconfig`

```
gsctl --api-endpoint https://api.g8s.iris.eu-central-1.aws.gigantic.io   create kubeconfig --cluster mns0f   --auth-token yolo

Creating new key pair…
New key pair created with ID 3903c631a… and expiry of 720 hours
```

Looks like the auth-token parameter is having no effect. I'd expect it to not care if I am logged in our not too:

```
gsctl --api-endpoint https://api.g8s.iris.eu-central-1.aws.gigantic.io \
  create kubeconfig --cluster mns0f \
  --auth-token aREALtokenHERE
Error: You are not logged in. Use 'gsctl login' to log in.
```

This breaks the getting started guide.

**Comment by marians** [comment]
For a few cases there are fixes in #120. Example: https://github.com/giantswarm/gsctl/pull/120/commits/0e071e0773c791c158a0521cdb0a3d3af672dedc

The right way to get endpoint and token to use:

```go
endpoint := config.Config.ChooseEndpoint(cmdAPIEndpoint)
token := config.Config.ChooseToken(endpoint, cmdToken)
```

This should be used in all commands.

**Comment by marians** [comment]
Reopening for another check

**Comment by marians** [comment]
Let's assume this is fixed.
