### ISSUE TITLE
Windows binary is considered a threat

### ISSUE THREAD

**Issue by trobert2** [giantswarm/gsctl#98]
Windows binary is considered a threat by the default security software installed on our laptops.
![windows binary](https://user-images.githubusercontent.com/4254749/27380225-9b47dbc4-567e-11e7-8a11-a82cc3cd5f61.png)

I would also like to know if the binaries are signed by a Microsoft authority?

**Comment by marians** [comment]
I'd say it's absolutely understandable to not trust an executable from any third party. Currently our windows binaries are not signed.

@trobert2 In your case, seems like you can execute the binary anyway, right? Will the warning disappear for good when you chose to "Allow this file"?

**Comment by trobert2** [comment]
@marians it will work for the current command executed for a certain (short) period. It also lags because the failed scan starts that GUI that you see in the screen capture so the command waits for approval.

**Comment by marians** [comment]
Here is a first attempt for a signed binary.

[gsctl-64bit-signed.exe.zip](https://github.com/giantswarm/gsctl/files/1094461/gsctl-64bit-signed.exe.zip)

**Comment by marians** [comment]
The binary below is signed with a proper code signing certificate. Please test if possible.

[gsctl.exe.zip](https://github.com/giantswarm/gsctl/files/1204591/gsctl.exe.zip)

**Comment by marians** [comment]
Update on the [comment above](https://github.com/giantswarm/gsctl/issues/98#issuecomment-320632891): The signature is NOT valid. No need to test.

**Comment by marians** [comment]
New attempt: [gsctl.exe.zip](https://github.com/giantswarm/gsctl/files/1204626/gsctl.exe.zip)

**Comment by marians** [comment]
According to my Windows 10 test instance, the EXE in the above ZIP is signed in a valid way.

![image](https://user-images.githubusercontent.com/273727/29024504-a7fc7c62-7b72-11e7-8ceb-936d5d2cc9e2.png)

**Comment by marians** [comment]
@trobert2 Have you tried the last signed binary attached? I'd like to know what your experience has been like with that one.

**Comment by marians** [comment]
Considering this done. As soon as a new version is released, it will be signed.
