### ISSUE TITLE
gsctl should work via a proxy

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#99]
Some users can only connect to their API server via a proxy server. `gsctl` should allow to connect through a proxy. How that is specified might depend on the platform.

Un unix, a convenient approach would be to use the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables if set. There is [ProxyFromEnvironment](https://golang.org/pkg/net/http/#ProxyFromEnvironment) for that purpose in Go.

How would an appropriate solution for Windows look like?

Independent of the platform, we should provide a global option to set these proxy details explicitly for gsctl. The assumption is that a URL contains all information required (protocol, port, host name or IP, and optionally basic auth credentials).

**Comment by trobert2** [comment]
I believe ProxyFromEnvironment will work on windows as well, as long as the variables are set under `env` as so:
```
$env:HTTP_PROXY="http://localhost:8080"
```

This was tested with:
```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	req, err := http.NewRequest("GET", "http://google.com", nil)
	url, err := http.ProxyFromEnvironment(req)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(url)
}
```
which has the desired outcome.

**Comment by marians** [comment]
Thank you very much @trobert2 for the test!

**Comment by marians** [comment]
> Independent of the platform, we should provide a global option to set these proxy details explicitly for gsctl. The assumption is that a URL contains all information required (protocol, port, host name or IP, and optionally basic auth credentials).

Since this works the same way on Unix and Windows, I think we can live with the environment variables for now, not providing a command line flag. Once the need comes up, we can of course add that option.
